version: '2.4'
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:ol-trunk
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=10.200.0.10
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SENHA
    volumes:
      - /srv/volumes/zabbix-server-module:/var/lib/zabbix/modules
    networks:
      zabbix-rede:
        ipv4_address: 10.200.0.7
 
  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-apache-pgsql:ubuntu-trunk
    restart: always
    pull_policy: always
    environment:
      - DB_SERVER_HOST=10.200.0.10
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SENHA
      - ZBX_SERVER_HOST=10.200.0.7
      - PHP_TZ=America/Sao_Paulo
    networks:
      zabbix-rede:
        ipv4_address: 10.200.0.8
    ports:
      - 8080:8080
      - 443:8443
    volumes:
      - /srv/volumes/zabbix-frontend/ssl.key:/etc/ssl/apache2/ssl.key
      - /srv/volumes/zabbix-frontend/ssl.crt:/etc/ssl/apache2/ssl.crt
 
  zabbix-pgsql:
    container_name: zabbix-pgsql
    image: postgres:15.1-bullseye
    restart: always
    environment:
      - POSTGRES_PASSWORD=SENHA
    volumes:
      - /srv/volumes/zabbix-pgsql:/var/lib/postgresql/data
    networks:
      zabbix-rede:
       ipv4_address: 10.200.0.10
    ports:
      - 5432:5432
 
networks:
  zabbix-rede:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
          gateway: 10.200.0.1
